version: '3'
services:
  aibooks_nextjs:
    container_name: aibooks_nextjs
    build: ./
  aibooks_nginx:
    container_name: aibooks_nginx
    depends_on:
      - aibooks_nextjs
    build: ./nginx
    ports:
      - 80:80