services:
  nextjs:
    container_name: aibooks_nextjs
    build: .
    restart: always
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`go.aibooks.ru`)"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"